services:
  - type: web
    name: b-sides-platform
    env: node
    buildCommand: npm run render-build
    startCommand: npm run render-start
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_SUPABASE_URL
        sync: false
      - key: NEXT_PUBLIC_SUPABASE_ANON_KEY
        sync: false 